### PR TITLE
Add scrollarea module

### PR DESCRIPTION
**Pull request by danielfdsilva**
Adds a proxy for the react-scrollbar module.

The [original module](https://github.com/souhe/reactScrollbar) didn't have the features we needed so it was forked and the features added. To facilitate maintenance on our side we created a proxy that just makes the module available under `OAM.ScrollArea`

### CODE REVIEW

**Comment by smit1678** [comment]
@danielfdsilva @ricardomestre Is this still in play and need to be reviewed and merged?

**Comment by danielfdsilva** [comment]
@smit1678 should be good to go, but I need to have another look. Feel free to test it though.

**Comment by smit1678** [comment]
Tested the branch. Is this the expected behavior? 

sandbox openaerialmap design system 2017-03-03 15-43-14

**Comment by smit1678** [comment]
Thumbs up from @danielfdsilva via Slack.

**Pull request merged**
